### ISSUE TITLE
Panics when trying single-threaded sort

### ISSUE THREAD

**Issue by jhorstmann** [Nessex/rdst#4]
The following program tries to sort using a single thread.

```rust
use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

use rdst::RadixSort;

const BATCH_SIZE: usize = 1_000_000;

fn sort_slice_rdst(data: &[f64]) -> Vec<f64> {
    let mut data = data.to_vec();
    data.radix_sort_builder().with_parallel(false).sort();
    data
}

#[test]
fn test_rdst() {
    let mut rng = StdRng::seed_from_u64(42);
    let data = (0..BATCH_SIZE)
        .map(|_| rng.gen_range(0..100_000) as f64)
        .collect::<Vec<f64>>();
    let _sorted = sort_slice_rdst(&data);
}
```

 With a BATCH_SIZE of 1_000_000 it fails with

```

Bad algorithm: MtLsb for len: 1000000
thread 'rdst_test::test_rdst' panicked at 'Bad algorithm: MtLsb for len: 1000000', /home/jhorstmann/.cargo/registry/src/github.com-1ecc6299db9ec823/rdst-0.20.3/src/sorter.rs:69:22
```

Another BATCH_SIZE of 10_000_000 fails with a different panic:

```

range end index 10000000 out of range for slice of length 1250000
thread 'rdst_test::test_rdst' panicked at 'range end index 10000000 out of range for slice of length 1250000', /home/jhorstmann/.cargo/registry/src/github.com-1ecc6299db9ec823/rdst-0.20.3/src/sorts/ska_sort.rs:61:18
```

**Comment by nessex** [comment]
Thanks for the report and the minimal example! I've just released `v0.20.5` which includes fixes for these two panics, and some tests so they don't come back. Please let me know if you see any further issues!

> The following program tries to sort using a single thread.

Just in case (apologies if you already know), you may want to take a second look at:
https://github.com/Nessex/rdst#single-threaded-variant

The example above isn't purely single-threaded. It will run just one radix sorting algorithm at a time, however it may still use a multi-threaded algorithm! If your use-case is purely single-threaded, I'd recommend turning off the `multi-threaded` crate feature entirely as it will ensure you don't spin up any extra threads at all, and also improve compile times / bloat.
