### ISSUE TITLE
Algorithm::MtLsb does not sort correctly

### ISSUE THREAD

**Issue by stijn-ucrowds** [Nessex/rdst#5]
While comparing algorithms I noticed that Algorithm::MtLsb does not always result in a sorted array. My datatype is a u32 and the vector is 40K values distributed over the range 0..4_000_000 with duplicate values here and there.

This is my implementation for the RadixKey trait (Yeet is a struct(u32, u32))
```rs
impl RadixKey for Yeet {
    const LEVELS: usize = 4;

    #[inline]
    fn get_level(&self, level: usize) -> u8 {
        (self.y >> (level * 8)) as u8
    }
}
```

**Comment by nessex** [comment]
Thanks for the report! I've just published `v0.20.6` which fixes this issue.

This was an issue with using the multi-threaded (tile-based) algorithms on inputs that are small enough to fit into a single tile. A check for already sorted input, used to skip unnecessary work, was getting tripped in this case when it shouldn't have been.

Side note: if `self.y` is a `u32` it already has `get_level()` implemented. You can simplify that implementation of `RadixKey` like this:

```rust
impl RadixKey for Yeet {
    const LEVELS: usize = 4;

    #[inline]
    fn get_level(&self, level: usize) -> u8 {
        self.y.get_level(level)
    }
}
```
